name: Promote staging to production
description: Create or reuse a PR from a head branch to a base branch.

inputs:
  head:
    description: Source branch (head)
    required: false
    default: staging
  base:
    description: Target branch (base)
    required: false
    default: main

runs:
  using: composite
  steps:
    - name: Create or reuse PR (head -> base)
      id: pr
      uses: actions/github-script@v7
      with:
        script: |
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          const head = '${{ inputs.head }}';
          const base = '${{ inputs.base }}';

          // Compare commits between base and head to see if there's anything to promote
          const comparison = await github.rest.repos.compareCommitsWithBasehead({
            owner,
            repo,
            basehead: `${base}...${head}`,
          });

          // If there are no commits to merge, exit early
          if (comparison.data.total_commits === 0) {
            core.info(`No changes to merge from ${head} into ${base}.`);
            core.setOutput('pr_number', '');
            core.setOutput('pr_url', '');
            return;
          }

          // Look for an existing open PR from head -> base
          const { data: prs } = await github.rest.pulls.list({
            owner,
            repo,
            state: 'open',
            base,
            head: `${owner}:${head}`,
            per_page: 1,
          });

          let pr = prs[0];

          // If no PR exists, create one
          if (!pr) {
            const created = await github.rest.pulls.create({
              owner,
              repo,
              head,
              base,
              title: 'Promote staging to production',
              body: 'This PR promotes all changes from staging to production.',
            });
            pr = created.data;
            core.info(`Created PR #${pr.number}: ${pr.html_url}`);
          } else {
            core.info(`Reusing existing PR #${pr.number}: ${pr.html_url}`);
          }

          // Expose PR details for the next step
          core.setOutput('pr_number', String(pr.number));
          core.setOutput('pr_url', pr.html_url);
